default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST']%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
 
development:
  <<: *default
  database: onebitforms_development
 
test:
  <<: *default
  database: onebitforms_test
 
production:
  <<: *default
  database: onebitforms_production